#!/bin/bash
# This script is used for submitting jobs to cluster.
# Job name: Sandwich/tank

#SBATCH --nodes=1
#SBATCH --cpus-per-task=12

#SBATCH -p mnf
#SBATCH --nodelist mnf149.csc.warwick.ac.uk

#SBATCH --mem-per-cpu=1024

#SBATCH --time=240:00:00

module load intel impi imkl

MY_NUM_THREADS=$SLURM_CPUS_PER_TASK

export OMP_NUM_THREADS=$MY_NUM_THREADS

srun lmp_mpi -in test.MD
#srun lmp_mpi -in tank.MD
#srun lmp_mpi -in Bins_Sandwich.MD
