#!/bin/bash
# This script is used for submitting jobs to cluster.
# Job name: ThinfilmTank

#SBATCH --nodes=1
#SBATCH --cpus-per-task=8

#SBATCH -p mnf
#SBATCH --nodelist mnf149.csc.warwick.ac.uk

#SBATCH --mem-per-cpu=2048

#SBATCH --time=48:00:00

module load intel impi imkl

MY_NUM_THREADS=$SLURM_CPUS_PER_TASK

export OMP_NUM_THREADS=$MY_NUM_THREADS

#srun lmp_mpi -in in.polymer_gk
srun lmp_mpi -in in.polymer_surface_tension
#srun lmp_mpi -in Bins_Sandwich.MD
