#!/bin/bash

# author: Jingbang Liu

# discription: load netCDF-Fortran/4.4.4 on cluster

module load GCC/7.3.0-2.30/

module load XZ/5.2.4/

module load OpenMPI/3.1.1/

module load netCDF-Fortran/4.4.4/

make
