#!/bin/bash
# This script is used for submitting jobs to cluster.
# Job name: read bins

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=8

#SBATCH --mem-per-cpu=8192

#SBATCH --time=168:00:00

module load GCC/7.3.0-2.30/
module load XZ/5.2.4/
module load OpenMPI/3.1.1/
module load netCDF-Fortran/4.4.4/

MY_NUM_THREADS=$SLURM_CPUS_PER_TASK

export OMP_NUM_THREADS=$MY_NUM_THREADS

./exec
